let mapleader=","

set nocompatible
set mouse=a
set shell=zsh

filetype on                 
filetype plugin on
filetype indent on

set foldenable 

set autoread

" vimdiff option to ignore whitespace comparison
set diffopt+=iwhite
set diffexpr=""


call plug#begin('~/.vim/plugged')
    Plug 'vim-airline/vim-airline' 
    Plug 'vim-airline/vim-airline-themes'
    " syntax
    Plug 'tpope/vim-markdown'
    Plug 'ap/vim-css-color' " displays colors in css file 
    " colorschemes 
    Plug 'morhetz/gruvbox'
call plug#end() 

let g:airline_powerline_fonts = 1 
let g:airline_theme = 'badwolf'

set scrolloff=4
set wildmenu
set wildmode=longest:full
set wildignore+=*/tmp/*,*/.cache/*,*/.git/*,*.so,*~,*.pyc,*.bak,*.class,*.swp,*.zip,*.pdf 
set wildignore+=*\\tmp\\*,*.exe  " Windows

set laststatus=2
set number
set relativenumber
set showcmd
set so=7
set ruler
set cmdheight=1
set hid

set backspace=eol,start,indent
set whichwrap+=<,>,h,l

set ignorecase
set smartcase
set hlsearch

set incsearch
set lazyredraw
set magic
set showmatch
set mat=2

set noerrorbells
set novisualbell
set t_vb=
set tm=500

set linespace=1

set secure

syntax enable
set t_Co=256
colorscheme gruvbox
set background=dark
set termguicolors

set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

set ffs=unix,mac,dos

set nobackup
set nowb
set noswapfile
set nowritebackup

set history=1000
set undofile   
set undolevels=1000
set undoreload=10000
set undodir=~/.vim/.undo,~tmp,/tmp
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swp//

set expandtab
set smarttab

set shiftwidth=4
set tabstop=4
set softtabstop=4

set lbr
set textwidth=500

set autoindent
set smartindent

set wrap
set completeopt=longest,menuone

set comments=sl:/*,mb:\ *,elx:\ */

set spelllang=en_us
set complete+=kspell
set nospell 

map <leader>w :w<cr> 
map <leader>r :!python3 a.py
map <leader>n :new<cr> 
map <leader>nv :vnew<cr>
map <leader>rc :!g++ a.cpp && ./a.out
map <leader>c :!xclip -sel c 

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

noremap <PageUp> <Nop>
noremap <PageDown> <Nop>

" disable entering in replace mode when pressing insert twice. You can still enter in replace mode using R
imap <Insert> <Nop>
inoremap <S-Insert> <Insert>

nnoremap x "_x
nnoremap X "_X
nnoremap d "_d
nnoremap D "_D
vnoremap d "_d
nnoremap <leader>d ""d
nnoremap <leader>D ""D
vnoremap <leader>d ""d

nnoremap Y y$
nnoremap yw yiw

nnoremap <silent><Tab>       :bn<CR> 
nnoremap <silent><S-Tab>     :bp<CR> 
nnoremap <silent><Leader>q   :bd<CR> 

nnoremap <silent> <leader>ev :e $MYVIMRC<CR>
nnoremap <silent> <leader>sv :so $MYVIMRC<CR>

nnoremap <leader><leader>v :vertical terminal<CR>
nnoremap <leader><leader>s :terminal<CR>


